services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  gateway-server:
    build: ./gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/userservice
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  notification-service:
    build: ./notification-service
    ports:
      - "9090:9090"
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
      db1:
        condition: service_healthy
      kafka:
        condition: service_started
      mailhog:
        condition: service_started
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/notificationservice
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  db1:
    image: postgres:16.1
    container_name: postgresNotificationService
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres-notification:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=notificationservice
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d notificationservice"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: postgres:16.1
    container_name: postgresUserServiceSpringBoot
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=userservice
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d userservice"]
      interval: 5s
      timeout: 5s
      retries: 10

  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INDOCKER://0.0.0.0:29092,OUTDOCKER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INDOCKER://kafka:29092,OUTDOCKER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INDOCKER:PLAINTEXT,OUTDOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INDOCKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      cub kafka-ready -b kafka:29092 1 20 &&
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user_notification --partitions 1 --replication-factor 1